
package introsde.dsantoro.dbws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "dbwsService", targetNamespace = "http://dbws.dsantoro.introsde/", wsdlLocation = "http://192.168.5.3:6902/ws/dbws?wsdl")
public class DbwsService
    extends Service
{

    private final static URL DBWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBWSSERVICE_EXCEPTION;
    private final static QName DBWSSERVICE_QNAME = new QName("http://dbws.dsantoro.introsde/", "dbwsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.3:6902/ws/dbws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBWSSERVICE_WSDL_LOCATION = url;
        DBWSSERVICE_EXCEPTION = e;
    }

    public DbwsService() {
        super(__getWsdlLocation(), DBWSSERVICE_QNAME);
    }

    public DbwsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBWSSERVICE_QNAME, features);
    }

    public DbwsService(URL wsdlLocation) {
        super(wsdlLocation, DBWSSERVICE_QNAME);
    }

    public DbwsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBWSSERVICE_QNAME, features);
    }

    public DbwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DbwsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Dbws
     */
    @WebEndpoint(name = "DbwsImplPort")
    public Dbws getDbwsImplPort() {
        return super.getPort(new QName("http://dbws.dsantoro.introsde/", "DbwsImplPort"), Dbws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dbws
     */
    @WebEndpoint(name = "DbwsImplPort")
    public Dbws getDbwsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dbws.dsantoro.introsde/", "DbwsImplPort"), Dbws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBWSSERVICE_EXCEPTION!= null) {
            throw DBWSSERVICE_EXCEPTION;
        }
        return DBWSSERVICE_WSDL_LOCATION;
    }

}
